apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${STORAGE_SERVER}
    path: "${STORAGE_SERVER_PATH}"
